RSpec/ExampleLength:
  Max: 10
RSpec/SubjectStub:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/MessageChain:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*